### PR TITLE
Update login command

### PR DESCRIPTION
**Pull request by jelneo**
- Update user guide for login command (CLI and GUI)
- Allow copy and pasting of command for login CLI version
- Fix parsing bug for GUI login

### CODE REVIEW

**Review by khooroko — COMMENTED** [review]
Perhaps you can make a callout for the sample account as well since it is the literally the most important piece of information in our user guide

**Review by khooroko — APPROVED** [review]
LGTM

**Review by lawwman — APPROVED** [review]
Approved

**Review by jaivigneshvenugopal — APPROVED** [review]
Nice!

**Pull request merged**
